import "./globals.css";
import Header from "./Components/Header/page";
import Footer from "./Components/Footer/page";
import { ToastContainer } from "react-toastify";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import "@uploadthing/react/styles.css";
import { HeroUIProvider } from "@heroui/react";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export const metadata = {
  title: "Alishaimpex",
  description: "Generated by create next app chemicals",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body>
        <HeroUIProvider>
          <Header />
          <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
          {children}
          <ToastContainer />
          <Footer />
        </HeroUIProvider>
      </body>
    </html>
  );
}
