import "./globals.css";
import Header from "./Components/Header/page";
import Footer from "./Components/Footer/page";
import { ToastContainer } from "react-toastify";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import "@uploadthing/react/styles.css";
import { HeroUIProvider } from "@heroui/react";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import SessionWrapper from "./Components/SessionWrapper/SessionWrapper";

export const metadata = {
  title: "Alishaimpex",
  description: "Generated by create next app chemicals",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionWrapper>
          <HeroUIProvider>
            <Header />
            <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
            {children}
            <ToastContainer />
            <Footer />
          </HeroUIProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
